# Generated by Django 3.2 on 2021-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance')], default='l', max_length=8)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='l', max_length=8)),
                ('production_date', models.DateField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
