# Generated by Django 3.2 on 2021-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='product_image',
            new_name='movie_image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('act', 'Action'), ('dra', 'Drama'), ('com', 'Comedy'), ('rom', 'Romance')], max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=8),
        ),
    ]
